apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: node-health-check
  namespace: argocd
spec:
  metrics:
  - name: health-check
    interval: 10s
    count: 5
    successCondition: result == 200
    failureLimit: 1
    provider:
      web:
        url: "http://node-service-canary.argocd.svc.cluster.local/health"