apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node
  template:
    metadata:
      labels:
        app: node
    spec:
      containers:
      - name: node-container
        image: anushkashukla003/node-app:3825e9e5be14e2e8dab5734fa5c6149786b2ef7a
        ports:
        - containerPort: 3000