apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node
  template:
    metadata:
      labels:
        app: node
    spec:
      containers:
      - name: node-container
        image: anushkashukla003/node-app:7a018469a14f55ce7879e7f1aee1602e60390333
        ports:
        - containerPort: 3000