apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: node-app
  namespace: argocd
spec:
  replicas: 2
  progressDeadlineSeconds: 60
  selector:
    matchLabels:
      app: node
  template:
    metadata:
      labels:
        app: node
    spec:
      containers:
      - name: node-container
        image: anushkashukla003/node-app:0b550293811b75c9a6c1efdacb97d63f5121322a
        ports:
        - containerPort: 3000
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          periodSeconds: 10
          failureThreshold: 5
          timeoutSeconds: 2
  strategy:
    canary:
      canaryService: node-service-canary
      stableService: node-service-stable
      steps:
      - setWeight: 20
      - analysis:
          templates:
          - templateName: node-health-check
      - pause:
          duration: 30s
      - setWeight: 50
      - pause:
          duration: 30s
      - setWeight: 100